# Generated by Django 2.0.5 on 2018-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('stockid', models.IntegerField(db_column='StockID', primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, db_column='Abbreviation', max_length=10, null=True, unique=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=128, null=True, unique=True)),
                ('employees', models.IntegerField(blank=True, db_column='Employees', null=True)),
                ('capital', models.BigIntegerField(blank=True, db_column='Capital', null=True)),
                ('industryname', models.CharField(db_column='IndustryName', max_length=16)),
                ('listeddate', models.CharField(blank=True, db_column='ListedDate', max_length=45, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
    ]
